name: Docker Image Build

on:
  push:
    branches: [ master ]

jobs:
  docker:
    name: Docker Image

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install java
      uses: actions/setup-java@v1
      with:
        java-version: '8.0.x'
        java-package: jdk
        architecture: x64

    - name: Run test
      run: ./gradlew test

    - name: Build result jar
      run: ./gradlew shadowJar

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build image
      run: docker build -t indexyz/catboat .

    - name: Push to docker hub
      uses: actions-hub/docker@master
      with:
        args: push indexyz/catboat
